version: '3.8'

services:
  voiceforge:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: voiceforge-app:dev
    container_name: voiceforge-app-dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
